import { z } from 'zod';

export const STORY_DIRECTOR_STATE_KEY = 'daoyuan_story_director_v1';
export const XUANTIAN_FAULT_LOG_KEY = 'daoyuan_xuantian_fault_log_v1';
const BranchSchema=z.object({id:z.string().trim().regex(/^[a-z0-9_-]+$/).max(120),trigger:z.string().trim().min(1).max(1000),playerFreedom:z.string().trim().min(1).max(1000),outcome:z.string().trim().min(1).max(1600),nextNodeId:z.string().trim().regex(/^[a-z0-9_-]+$/).max(120).nullable()});
const NodeSchema=z.object({id:z.string().trim().regex(/^[a-z0-9_-]+$/).max(120),title:z.string().trim().min(1).max(300),status:z.enum(['locked','available','current','resolved','skipped']),dramaticQuestion:z.string().trim().min(1).max(1200),observableSetup:z.string().trim().min(1).max(2000),stakes:z.string().trim().min(1).max(1200),branches:z.array(BranchSchema).min(1).max(8),invalidatedWhen:z.string().trim().min(1).max(1000)});
export const StoryDirectorPlanSchema=z.object({schemaVersion:z.literal(1),chatId:z.string().min(1),sequence:z.number().int().nonnegative(),revision:z.number().int().positive(),mode:z.enum(['观察','轻触发','成篇','自由生活']),confidence:z.number().min(0).max(1),assessment:z.string().trim().min(1).max(4000),interests:z.array(z.string().trim().min(1).max(500)).max(12),avoidances:z.array(z.string().trim().min(1).max(500)).max(12),evidence:z.array(z.string().trim().min(1).max(800)).max(16),arcId:z.string().trim().regex(/^[a-z0-9_-]+$/).max(120),arcTitle:z.string().trim().min(1).max(300),arcStatus:z.enum(['observing','active','suspended','closed']),currentNodeId:z.string().trim().regex(/^[a-z0-9_-]+$/).max(120).nullable(),nodes:z.array(NodeSchema).min(1).max(12),historySummary:z.string().trim().max(4000)});
export type StoryDirectorPlan=z.infer<typeof StoryDirectorPlanSchema>;
export interface XuantianFaultLog { at:string;level:'info'|'retry'|'error';sequence:number;requestCount:number;message:string;detail?:string; }
export function validateStoryDirectorGraph(plan:StoryDirectorPlan):StoryDirectorPlan{const ids=new Set(plan.nodes.map(node=>node.id));if(ids.size!==plan.nodes.length)throw new Error('剧情图节点 ID 重复');if(plan.currentNodeId&&!ids.has(plan.currentNodeId))throw new Error('剧情图当前节点不存在');for(const node of plan.nodes)for(const branch of node.branches)if(branch.nextNodeId&&!ids.has(branch.nextNodeId))throw new Error(`剧情分支引用未知节点：${branch.nextNodeId}`);return plan;}
export function validateStoryDirectorTransition(previous:StoryDirectorPlan|null,next:StoryDirectorPlan):StoryDirectorPlan{if(!previous)return next;if(next.chatId!==previous.chatId)throw new Error('剧情图聊天标识发生变化');if(next.revision!==previous.revision+1)throw new Error(`剧情图修订号必须从 ${previous.revision} 前进到 ${previous.revision+1}`);if(next.arcId===previous.arcId){for(const oldNode of previous.nodes.filter(node=>node.status==='resolved'||node.status==='skipped')){const newNode=next.nodes.find(node=>node.id===oldNode.id);if(!newNode||JSON.stringify(newNode)!==JSON.stringify(oldNode))throw new Error(`已发生剧情节点不得改写：${oldNode.id}`);}}return next;}
