import { z } from 'zod';

export const BRIDGE_PROTOCOL = 1;

export const BridgeActionSchema = z.enum([
  'APP_READY',
  'REQUEST_CONTEXT',
  'SET_LAYOUT',
  'SET_ACTIVE_APP',
  'SET_PET_SIZE',
  'SET_PET_KIND',
  'SET_MAP_VIEW',
  'CLOSE_SHELL',
  'REQUEST_DIAGNOSTIC',
  'REQUEST_MVU_CHANNEL',
  'MVU_CHANNEL_SNAPSHOT',
  'REPLACE_MVU_CHANNEL_STAT_DATA',
  'MVU_CHANNEL_WRITE_STATUS',
  'SEND_YUJIAN_MESSAGE',
  'YUJIAN_SEND_STATUS',
  'REQUEST_YUJIAN_LORE',
  'YUJIAN_LORE_DATA',
  'REQUEST_YUJIAN_MODELS',
  'YUJIAN_MODELS_DATA',
  'REQUEST_EARTH_MODELS',
  'EARTH_MODELS_DATA',
  'REQUEST_XUANTIAN_MODELS',
  'XUANTIAN_MODELS_DATA',
  'SAVE_XUANTIAN_SETTINGS',
  'XUANTIAN_SETTINGS_STATUS',
  'GENERATE_XUANTIAN_SIMULATION',
  'XUANTIAN_SIMULATION_STATUS',
  'RESET_XUANTIAN_SIMULATION',
  'XUANTIAN_SIMULATION_RESET_STATUS',
  'SAVE_EARTH_SETTINGS',
  'EARTH_SETTINGS_STATUS',
  'GENERATE_EARTH_SIMULATION',
  'EARTH_SIMULATION_STATUS',
  'RESET_EARTH_SIMULATION',
  'EARTH_SIMULATION_RESET_STATUS',
  'CLEAR_EARTH_SIMULATION',
  'CLEAR_XUANTIAN_SIMULATION',
  'WORLD_SIMULATION_CLEAR_STATUS',
  'SAVE_YUJIAN_SETTINGS',
  'IMPORT_STATUS_YUJIAN_HISTORY',
  'YUJIAN_HISTORY_IMPORT_STATUS',
  'DELETE_YUJIAN_MESSAGE',
  'CLEAR_YUJIAN_HISTORY',
  'YUJIAN_HISTORY_DELETE_STATUS',
  'DELETE_YUJIAN_CONTACT',
  'YUJIAN_CONTACT_DELETE_STATUS',
  'REQUEST_BEAUTY_MODELS',
  'BEAUTY_MODELS_DATA',
  'SAVE_BEAUTY_SETTINGS',
  'BEAUTY_SETTINGS_STATUS',
  'REQUEST_XIANWANG_MODELS',
  'XIANWANG_MODELS_DATA',
  'SAVE_XIANWANG_SETTINGS',
  'XIANWANG_SETTINGS_STATUS',
  'REQUEST_WANBAO_MODELS', 'WANBAO_MODELS_DATA', 'SAVE_WANBAO_API_SETTINGS', 'WANBAO_SETTINGS_STATUS',
  'SAVE_PROMPT_INJECTION_SETTINGS',
  'PROMPT_INJECTION_SETTINGS_STATUS',
  'GENERATE_TRENDS',
  'TRENDS_GENERATION_STATUS',
  'DELETE_TREND',
  'TREND_DELETE_STATUS',
  'GENERATE_FORUM', 'FORUM_GENERATION_STATUS', 'DELETE_FORUM_POST', 'FORUM_DELETE_STATUS',
  'TOGGLE_TREND_LIKE', 'TOGGLE_FORUM_LIKE', 'TOGGLE_NEWS_LIKE',
  'SUBMIT_FORUM_COMMENT', 'FORUM_COMMENT_STATUS',
  'GENERATE_NEWS', 'NEWS_GENERATION_STATUS', 'DELETE_NEWS_PAPER', 'NEWS_DELETE_STATUS',
  'GENERATE_BEAUTY_RANK',
  'BEAUTY_GENERATION_STATUS',
  'GENERATE_BEAUTY_REPLY',
  'BEAUTY_REPLY_STATUS',
  'GENERATE_WANBAO', 'WANBAO_GENERATION_STATUS', 'ESTIMATE_WANBAO', 'WANBAO_ESTIMATE_STATUS', 'BUY_WANBAO', 'SELL_WANBAO', 'WANBAO_TRADE_STATUS', 'DELETE_WANBAO_PRODUCT', 'DELETE_WANBAO_TRANSACTION', 'CLEAR_WANBAO_TRANSACTIONS',
  'REQUEST_DLC_STATUS', 'DLC_STATUS_DATA', 'INSTALL_MISSING_DLCS', 'DLC_INSTALL_STATUS',
  'ATTACH_DLCS_TO_CURRENT_CHARACTER', 'DLC_ATTACH_STATUS', 'SAVE_DLC_SETTINGS', 'DLC_SETTINGS_STATUS',
  'CHECK_DLC_COMPATIBILITY', 'DLC_COMPATIBILITY_DATA', 'REPAIR_DLC_MISSING_ENTRIES', 'DLC_REPAIR_STATUS',
  'UPDATE_INSTALLED_DLCS', 'DLC_UPDATE_STATUS',
  'IMPORT_CONTENT_PACKAGE', 'CONTENT_PACKAGE_IMPORT_STATUS',
  'SET_USER_SCRIPT_ENABLED', 'USER_SCRIPT_STATUS',
  'IMPORT_USER_DLC', 'USER_DLC_IMPORT_STATUS', 'REQUEST_USER_DLC_STATUS', 'USER_DLC_STATUS_DATA',
  'REPAIR_USER_DLC_MOUNT', 'USER_DLC_REPAIR_STATUS', 'REMOVE_USER_DLC', 'USER_DLC_REMOVE_STATUS',
  'REMOVE_USER_DLC_SCRIPT', 'USER_DLC_SCRIPT_REMOVE_STATUS',
  'REQUEST_EARTH_WORLDBOOK_STATUS', 'EARTH_WORLDBOOK_STATUS_DATA',
  'INSTALL_EARTH_WORLDBOOK', 'EARTH_WORLDBOOK_INSTALL_STATUS',
  'ATTACH_EARTH_WORLDBOOK', 'EARTH_WORLDBOOK_ATTACH_STATUS',
  'REPAIR_EARTH_WORLDBOOK', 'EARTH_WORLDBOOK_REPAIR_STATUS',
  'SAVE_CONTENT_BEAUTIFIER_SETTINGS', 'CONTENT_BEAUTIFIER_SETTINGS_STATUS',
  'SAVE_CONFIG_HELPER_SETTINGS', 'CONFIG_HELPER_SETTINGS_STATUS',
  'SAVE_FEATURE_MODULE_FLAGS', 'FEATURE_MODULE_FLAGS_STATUS',
  'SAVE_WORLD_SIMULATION_FEATURES', 'WORLD_SIMULATION_FEATURES_STATUS',
]);

export type BridgeAction = z.infer<typeof BridgeActionSchema>;

export const BridgeEnvelopeSchema = z.object({
  protocol: z.literal(BRIDGE_PROTOCOL),
  kind: z.enum(['request', 'event', 'response']),
  action: BridgeActionSchema,
  payload: z.record(z.string(), z.unknown()).default({}),
  contextRevision: z.number().int().nonnegative().default(0),
});

export type BridgeEnvelope = z.infer<typeof BridgeEnvelopeSchema>;

export function makeBridgeMessage(
  kind: BridgeEnvelope['kind'],
  action: BridgeAction,
  payload: Record<string, unknown> = {},
  contextRevision = 0,
): BridgeEnvelope {
  return { protocol: BRIDGE_PROTOCOL, kind, action, payload, contextRevision };
}

export function parseBridgeMessage(value: unknown): BridgeEnvelope | null {
  const result = BridgeEnvelopeSchema.safeParse(value);
  return result.success ? result.data : null;
}
