import { XuantianSimulationStateSchema } from './schema.ts';
import type { XuantianEventPhase, XuantianSimulationAction, XuantianSimulationState } from './types.ts';

const PHASES:XuantianEventPhase[]=['苗头','酝酿','发展','高潮','收束'];
export function xuantianSimulationReducer(state:XuantianSimulationState,action:XuantianSimulationAction):XuantianSimulationState {
  let next:XuantianSimulationState;
  if(action.type==='advance-world-days'){if(!Number.isInteger(action.days)||action.days<1||action.days>30)throw new Error('单次玄天界时间只允许推进1-30日');next={...state,worldDay:state.worldDay+action.days};}
  else if(action.type==='set-calendar-label')next={...state,calendarLabel:action.label.slice(0,120)};
  else if(action.type==='set-region-state'){const region=state.regions[action.regionId];next={...state,regions:{...state.regions,[action.regionId]:{...region,status:action.status,pressure:Math.max(0,Math.min(100,region.pressure+Math.trunc(action.pressureDelta??0))),summary:action.summary.slice(0,1000),updatedAtDay:state.worldDay}}};}
  else if(action.type==='set-faction-state'){const faction=state.factions[action.factionId];if(!faction)throw new Error(`未找到原版势力：${action.factionId}`);next={...state,factions:{...state.factions,[action.factionId]:{...faction,status:action.status,relation:action.relation??faction.relation,influence:Math.max(0,Math.min(100,faction.influence+Math.trunc(action.influenceDelta??0))),activity:action.activity.slice(0,1000),updatedAtDay:state.worldDay}}};}
  else if(action.type==='create-event'){if(state.events.some(event=>event.id===action.event.id))throw new Error(`事件线ID已存在：${action.event.id}`);if(state.events.filter(event=>event.status==='active').length>=24)throw new Error('活跃事件线已达上限');for(const id of action.event.factionIds)if(!state.factions[id])throw new Error(`事件引用了未知势力：${id}`);next={...state,events:[...state.events,{...action.event,phase:'苗头',progress:5,status:'active',startedAtDay:state.worldDay,updatedAtDay:state.worldDay}]};}
  else {const event=state.events.find(item=>item.id===action.eventId);if(!event)throw new Error(`未找到事件线：${action.eventId}`);if(event.status==='closed')throw new Error('已关闭事件线不能继续推进');if(action.type==='close-event'){if(event.phase!=='收束')throw new Error('事件线只有进入收束阶段后才能关闭');next={...state,events:state.events.map(item=>item.id===event.id?{...item,status:'closed',progress:100,summary:action.summary.slice(0,1000),consequence:action.consequence.slice(0,1000),updatedAtDay:state.worldDay}:item)};}else{const current=PHASES.indexOf(event.phase),target=PHASES.indexOf(action.nextPhase);if(target!==current+1)throw new Error('事件线每次只能推进一个阶段');if(action.progress<=event.progress)throw new Error('事件进度必须增加');next={...state,events:state.events.map(item=>item.id===event.id?{...item,phase:action.nextPhase,progress:Math.min(99,action.progress),summary:action.summary.slice(0,1000),consequence:(action.consequence??item.consequence).slice(0,1000),updatedAtDay:state.worldDay}:item)};}}
  return XuantianSimulationStateSchema.parse(next) as XuantianSimulationState;
}
